# Generated by Django 4.2.6 on 2023-10-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
