# Generated by Django 4.2.6 on 2023-10-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rung', '0002_alter_menu_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='description',
            new_name='description_1',
        ),
        migrations.AddField(
            model_name='menu',
            name='description_2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
