# Generated by Django 4.2.6 on 2023-10-24 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rung', '0003_rename_description_menu_description_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_germen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(default=0, null=True)),
                ('description_1', models.CharField(max_length=200, null=True)),
                ('description_2', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='addon_drink',
            name='menu_germen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rung.menu_germen'),
        ),
        migrations.AddField(
            model_name='addon_food',
            name='menu_germen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rung.menu_germen'),
        ),
    ]
