# Generated by Django 4.2.6 on 2023-10-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rung', '0004_menu_germen_addon_drink_menu_germen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menu_germen',
            name='description_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
