# Generated by Django 4.2 on 2023-10-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rung', '0005_alter_menu_description_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(max_length=20),
        ),
    ]
