# Generated by Django 4.2 on 2023-11-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rung', '0009_orderitem_cost_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
