# Generated by Django 4.2 on 2023-11-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rung', '0010_order_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
