# Generated by Django 4.2 on 2023-11-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rung', '0011_delete_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='country_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=200)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu_germen',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
