# Generated by Django 4.2 on 2023-11-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rung', '0012_country_code_menu_available_menu_germen_available'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='country_code',
            new_name='countrycode',
        ),
    ]
