# Generated by Django 4.2.6 on 2024-01-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rung', '0015_remove_holiday_notes_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycode',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
