# Generated by Django 4.2.6 on 2024-01-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rung', '0019_alter_shop_time_shop_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
