# Generated by Django 4.2.6 on 2024-01-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rung', '0020_contact_us_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code_amount',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charges',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
