# Generated by Django 4.2.6 on 2024-03-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rung', '0021_order_coupon_code_amount_order_delivery_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount_coupon_germen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=200)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('coupon_name', models.CharField(max_length=200)),
                ('coupon_description', models.TextField(blank=True, null=True)),
                ('coupon_expiry_date', models.DateField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
